AWSTemplateFormatVersion: '2010-09-09'

Resources:
  IAMUser1:
    Type: AWS::IAM::User
    Properties:
      Path: /
      UserName: IAMUser1

  IAMUser1AccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref IAMUser1

  IAMUser1AccessKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${IAMUser1}-credentials
      SecretString: !Sub "{\"accessKeyId\":\"${IAMUser1AccessKey}\",\"secretAccessKey\":\"${IAMUser1AccessKey.SecretAccessKey}\"}"
